import { StyleSheet } from 'react-native';

import { lightPalette, type Palette } from './palette';

function createStyles(palette: Palette) {
  return StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.bg },
  screen: { flex: 1, backgroundColor: palette.bg },
  splash: {
    flex: 1,
    backgroundColor: palette.splashNavy,
  },
  roleSelectionScreen: {
    flex: 1,
    backgroundColor: palette.roleSelectionBlue,
  },
  roleSelectionScrollContent: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 540,
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 42,
  },
  roleSelectionBody: {
    width: '100%',
    alignItems: 'center',
    flexGrow: 1,
    paddingTop: 30,
    paddingBottom: 22,
  },
  roleSelectionBrand: {
    width: '100%',
    alignItems: 'center',
  },
  roleSelectionLogo: {
    width: 96,
    height: 96,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.blueAction,
  },
  roleSelectionBrandTitle: {
    marginTop: 26,
    color: palette.roleSelectionText,
    fontSize: 42,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 50,
    textAlign: 'center',
  },
  roleSelectionTagline: {
    marginTop: 8,
    color: palette.roleSelectionMuted,
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'center',
  },
  roleSelectionPrompt: {
    width: '100%',
    alignItems: 'center',
    marginTop: 42,
    marginBottom: 20,
    gap: 8,
  },
  roleSelectionTitle: {
    color: palette.roleSelectionText,
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 30,
    textAlign: 'center',
  },
  roleSelectionSubtitle: {
    color: palette.roleSelectionMuted,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    textAlign: 'center',
  },
  roleSelectionCards: {
    width: '100%',
    gap: 16,
    marginTop: 'auto',
  },
  roleSelectionCard: {
    width: '100%',
    minHeight: 114,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  roleSelectionStudentCard: {
    backgroundColor: palette.white,
    borderColor: 'rgba(255,255,255,0.92)',
  },
  roleSelectionStaffCard: {
    backgroundColor: palette.roleSelectionStaffSurface,
    borderColor: palette.roleSelectionStaffBorder,
  },
  roleSelectionIcon: {
    width: 62,
    height: 62,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roleSelectionStudentIcon: {
    backgroundColor: palette.mint,
  },
  roleSelectionStaffIcon: {
    backgroundColor: palette.roleSelectionStaffIcon,
  },
  roleSelectionCardCopy: {
    flex: 1,
    gap: 8,
    minWidth: 0,
  },
  roleSelectionStudentTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 26,
  },
  roleSelectionStudentSubtitle: {
    color: palette.muted,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  roleSelectionStaffTitle: {
    color: palette.roleSelectionText,
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 26,
  },
  roleSelectionStaffSubtitle: {
    color: palette.roleSelectionMuted,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  roleSelectionFooter: {
    alignItems: 'center',
    paddingTop: 18,
  },
  roleSelectionFooterText: {
    color: palette.roleSelectionMuted,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  splashLanding: {
    backgroundColor: palette.splashNavy,
    overflow: 'hidden',
  },
  splashScroll: { flex: 1 },
  splashScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 28,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingTop: 24,
    paddingBottom: 16,
  },
  splashLandingScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 20,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  splashTopBar: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  splashEyebrow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  splashEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: palette.splashAccent,
  },
  splashEyebrowText: {
    color: palette.splashEyebrow,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.6,
  },
  splashCenter: {
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
    paddingTop: 18,
    paddingBottom: 126,
    gap: 16,
  },
  splashRestore: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  splashRestoreBrand: {
    alignItems: 'center',
    gap: 6,
  },
  splashHero: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
    marginBottom: 34,
  },
  splashHeroCopy: {
    alignItems: 'center',
    gap: 6,
  },
  splashLogo: {
    width: 88,
    height: 88,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: palette.blue,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: palette.blueShadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 4,
  },
  ticketStack: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: palette.blueSoft,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
  },
  ticketMark: { color: palette.blue, fontSize: 34, fontWeight: '900' },
  brand: { color: palette.ink, fontSize: 38, fontWeight: '800', letterSpacing: 0, lineHeight: 46 },
  tagline: { color: palette.splashTagline, fontSize: 17, fontWeight: '500', letterSpacing: 0, lineHeight: 24 },
  splashDescription: {
    maxWidth: 330,
    marginTop: 2,
    color: palette.muted,
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 23,
    textAlign: 'center',
  },
  splashStartButton: {
    width: '100%',
    minHeight: 104,
    maxWidth: 420,
    borderRadius: 22,
    backgroundColor: palette.splashTeal,
    paddingHorizontal: 18,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    borderWidth: 1,
    borderColor: palette.splashButtonBorder,
    boxShadow: palette.splashButtonShadow,
    elevation: 8,
  },
  splashStartButtonLower: {
    position: 'absolute',
    bottom: 22,
    alignSelf: 'center',
  },
  splashStartButtonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  splashStartButtonCopy: { flex: 1, gap: 5, minWidth: 0, flexShrink: 1 },
  splashStartButtonEyebrow: {
    color: palette.splashTextAccent,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  splashStartButtonTitle: {
    color: palette.splashTextButton,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 26,
  },
  splashStartButtonSubtitle: { color: palette.splashTextButton, fontSize: 12.5, fontWeight: '500', lineHeight: 17 },
  splashStartButtonArrow: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.splashArrowSurface,
  },
  splashFooter: { alignItems: 'center', paddingTop: 16, width: '100%' },
  splashFooterRule: {
    width: '100%',
    height: 1,
    marginBottom: 14,
    backgroundColor: palette.splashFooterRule,
  },
  splashFooterText: {
    color: palette.splashTextMuted,
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 0.2,
    lineHeight: 16,
    textAlign: 'center',
  },
  chooseRoleBackButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
  },
  chooseRoleBackText: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  chooseRoleContent: {
    width: '100%',
    maxWidth: 460,
    flexGrow: 1,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    paddingVertical: 24,
  },
  chooseRoleHero: { width: '100%', alignItems: 'center', gap: 10, marginBottom: 10 },
  chooseRoleEyebrow: {
    color: palette.amber,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.4,
    textAlign: 'center',
  },
  chooseRoleTitle: { color: palette.ink, fontSize: 27, fontWeight: '900', textAlign: 'center' },
  chooseRoleSubtitle: {
    maxWidth: 340,
    color: palette.muted,
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 22,
    textAlign: 'center',
  },
  rolePrompt: { width: '100%', gap: 7, marginTop: 8, marginBottom: 6 },
  rolePromptTitle: { color: palette.ink, fontSize: 22, fontWeight: '800', textAlign: 'center' },
  rolePromptSubtitle: { color: palette.muted, fontSize: 15, fontWeight: '500', textAlign: 'center' },
  roleCard: {
    width: '100%',
    minHeight: 90,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.faint,
    backgroundColor: palette.card,
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  roleIcon: {
    width: 54,
    height: 54,
    borderRadius: 17,
    backgroundColor: palette.blueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roleIconOnSplash: { backgroundColor: palette.warm },
  roleIconText: { color: palette.greenDark },
  roleCardCopy: { flex: 1, gap: 4, minWidth: 0, flexShrink: 1 },
  roleCardTitle: { color: palette.ink, fontSize: 17, fontWeight: '900' },
  roleCardSubtitle: { color: palette.muted, fontSize: 12.5, fontWeight: '600', lineHeight: 17 },
  roleArrow: { color: palette.muted },
  splashTrustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    marginTop: 5,
  },
  splashTrustDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: palette.splashAccentBright,
  },
  splashTrustText: { color: palette.muted, fontSize: 13, fontWeight: '600', textAlign: 'center' },
  roleSwitchButton: { alignItems: 'center', justifyContent: 'center', minHeight: 48 },
  roleSwitchText: { color: palette.blue, fontSize: 13, fontWeight: '800', textAlign: 'center' },
  dots: { flexDirection: 'row', gap: 8 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.splashTeal },
  dotMuted: { backgroundColor: palette.splashMuted, opacity: 0.6 },
  footerText: { color: palette.muted, fontSize: 12, fontWeight: '500' },
  primaryButton: {
    minHeight: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenDark,
    paddingVertical: 12,
    paddingHorizontal: 18,
    shadowColor: palette.greenDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryButtonMuted: { opacity: 0.72 },
  splashButton: { width: 200 },
  primaryButtonText: { color: palette.white, fontSize: 16, fontWeight: '900' },
  secondaryButton: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: palette.faint,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.card,
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  secondaryButtonText: { color: palette.ink, fontSize: 16, fontWeight: '900' },
  loginHero: { alignItems: 'center', paddingTop: 28, paddingBottom: 30, gap: 8 },
  schoolShield: {
    width: 68,
    height: 68,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.blue,
    shadowColor: palette.blueShadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 4,
  },
  schoolShieldText: { color: palette.white, fontSize: 24, fontWeight: '900' },
  schoolName: {
    marginTop: 8,
    color: palette.ink,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    flexShrink: 1,
  },
  mutedCenter: {
    color: palette.muted,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    maxWidth: 360,
    flexShrink: 1,
  },
  resetIcon: {
    width: 76,
    height: 76,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.splashTeal,
  },
  resetBackButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
  },
  resetBackText: { color: palette.blue, fontSize: 14, fontWeight: '800' },
  form: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 16,
  },
  authContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 24,
    gap: 24,
  },
  fieldBlock: { gap: 8 },
  label: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  inputShell: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: palette.faint,
    borderRadius: 16,
    backgroundColor: palette.card,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
  },
  inputShellFocused: { borderColor: palette.greenDark },
  inputShellError: { borderColor: palette.danger, backgroundColor: palette.dangerSoft },
  input: { flex: 1, minWidth: 0, color: palette.ink, fontSize: 14, fontWeight: '600' },
  fieldErrorRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  fieldError: { color: palette.danger, fontSize: 12, fontWeight: '700', flex: 1, minWidth: 0, flexShrink: 1 },
  errorBanner: {
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: palette.dangerSoft,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
  },
  errorBannerText: { color: palette.danger, fontSize: 13, fontWeight: '700', flex: 1, minWidth: 0, flexShrink: 1, lineHeight: 18 },
  errorDismiss: { color: palette.danger, fontSize: 12, fontWeight: '900' },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 164,
    paddingHorizontal: 24,
    paddingVertical: 22,
    borderWidth: 1,
    borderColor: palette.faint,
    borderRadius: 18,
    backgroundColor: palette.card,
  },
  emptyStateIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mint,
    marginBottom: 4,
  },
  emptyStateTitle: { color: palette.ink, fontSize: 15, fontWeight: '900', textAlign: 'center' },
  emptyStateMessage: { color: palette.muted, fontSize: 13, fontWeight: '600', lineHeight: 19, textAlign: 'center' },
  eyeText: { color: palette.muted, fontSize: 11, fontWeight: '900' },
  linkText: { color: palette.blue, textAlign: 'right', fontWeight: '800', fontSize: 14 },
  forgotPasswordLink: { minHeight: 44, alignItems: 'flex-end', justifyContent: 'center', marginTop: -8 },
  loginActions: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    marginTop: 'auto',
    paddingHorizontal: 20,
    paddingBottom: 28,
    gap: 20,
  },
  dividerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  divider: { flex: 1, height: 1, backgroundColor: palette.faint },
  dividerText: { color: palette.muted, fontSize: 13, fontWeight: '700' },
  content: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 28,
    gap: 18,
  },
  confirmationContent: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 30,
    gap: 26,
  },
  confirmationHeader: {
    alignItems: 'center',
    gap: 20,
    paddingVertical: 16,
  },
  confirmationAvatar: {
    width: 104,
    height: 104,
    borderRadius: 52,
  },
  confirmationTitle: {
    width: '100%',
    maxWidth: 540,
    textAlign: 'center',
    lineHeight: 34,
  },
  confirmationDescription: {
    width: '100%',
    maxWidth: 520,
    color: palette.muted,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 25,
    fontWeight: '600',
  },
  confirmationStatusCard: {
    width: '100%',
    minHeight: 120,
    borderRadius: 24,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 24,
    gap: 14,
    justifyContent: 'center',
  },
  confirmationStatusValue: {
    color: palette.ink,
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '900',
  },
  confirmationButtonStack: {
    marginTop: 'auto',
    gap: 16,
  },
  confirmationButton: {
    minHeight: 60,
  },
  appointmentQrCard: {
    width: '100%',
    alignItems: 'center',
    borderRadius: 24,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 22,
    gap: 16,
  },
  scannerPermissionCard: {
    borderRadius: 20,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 20,
    gap: 16,
  },
  scannerFrame: {
    height: 360,
    overflow: 'hidden',
    borderRadius: 24,
    backgroundColor: palette.scannerBackdrop,
  },
  scannerCamera: {
    flex: 1,
  },
  scannerHint: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  scheduleSavedBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: palette.scheduleSavedBackdrop,
  },
  scheduleSavedDialog: {
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
    borderRadius: 26,
    padding: 28,
    gap: 16,
    backgroundColor: palette.card,
  },
  scheduleSavedIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mint,
  },
  scheduleSavedIconText: {
    color: palette.greenDark,
    fontSize: 30,
    fontWeight: '900',
  },
  scheduleSavedTitle: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: '900',
  },
  scheduleSavedDoneButton: {
    width: '100%',
    alignSelf: 'stretch',
  },
  buttonStack: { width: '100%', gap: 12, marginTop: 4 },
  appointmentStatusCard: {
    borderRadius: 20,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 12,
  },
  upcomingAppointmentApproved: {
    gap: 14,
  },
  homeWelcomeCard: {
    borderRadius: 24,
    backgroundColor: palette.homeWelcomeTeal,
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 3,
  },
  homeWelcomeCardCompact: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  homeWelcomeCopy: { flex: 1, gap: 5, minWidth: 0, flexShrink: 1 },
  homeWelcomeEyebrow: { color: palette.white, fontSize: 12.5, fontWeight: '700' },
  homeWelcomeTitle: {
    color: palette.white,
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 30,
    minWidth: 0,
    flexShrink: 1,
  },
  homeWelcomeTitleCompact: {
    fontSize: 21,
    lineHeight: 26,
  },
  homeWelcomeSubtitle: {
    color: palette.white,
    fontSize: 12.5,
    fontWeight: '600',
    lineHeight: 18,
    minWidth: 0,
    flexShrink: 1,
  },
  homeWelcomeSubtitleCompact: {
    fontSize: 12,
    lineHeight: 16,
  },
  homeWelcomeAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: palette.white,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  homeWelcomeAvatarCompact: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  homeWelcomeAvatarText: { color: palette.homeWelcomeTeal, fontSize: 17, fontWeight: '900' },
  homeWelcomeAvatarTextCompact: { fontSize: 15 },
  verificationScreen: { gap: 18, paddingTop: 8 },
  verificationHero: { alignItems: 'center', gap: 12, paddingHorizontal: 12, paddingVertical: 12 },
  verificationIcon: {
    width: 82,
    height: 82,
    borderRadius: 28,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verificationTitle: { color: palette.ink, fontSize: 25, fontWeight: '900', textAlign: 'center' },
  verificationSubtitle: {
    maxWidth: 360,
    color: palette.muted,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 21,
    textAlign: 'center',
  },
  verificationEmail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.successBorder,
    backgroundColor: palette.successSurface,
    padding: 15,
  },
  verificationEmailIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: palette.successIconSurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verificationEmailCopy: { flex: 1, gap: 3 },
  verificationHint: { color: palette.muted, fontSize: 12, fontWeight: '700' },
  verificationAddress: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  verificationSteps: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 17,
    gap: 16,
  },
  verificationStep: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  verificationStepIcon: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verificationStepNumber: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: palette.blueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verificationStepNumberText: { color: palette.blue, fontSize: 12, fontWeight: '900' },
  verificationStepText: { flex: 1, color: palette.ink, fontSize: 13, fontWeight: '700' },
  verificationLoginButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  verificationLoginText: { color: palette.blue, fontSize: 14, fontWeight: '900' },
  verificationNotice: {
    color: palette.greenDark,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    textAlign: 'center',
  },
  profileDetails: {
    borderRadius: 20,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    paddingHorizontal: 16,
  },
  profileDetailRow: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    borderBottomWidth: 1,
    borderBottomColor: palette.faint,
  },
  profileDetailLabel: { color: palette.muted, fontSize: 13, fontWeight: '700' },
  profileDetailValue: { flex: 1, color: palette.ink, fontSize: 14, fontWeight: '800', textAlign: 'right' },
  profileStatus: { color: palette.greenDark, fontSize: 12, fontWeight: '900' },
  profileLoading: { minHeight: 130, alignItems: 'center', justifyContent: 'center', gap: 12 },
  staffApplicationNotice: {
    marginHorizontal: 24,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.infoBorder,
    backgroundColor: palette.infoSurface,
    padding: 18,
    gap: 8,
  },
  staffApplicationNoticeTitle: { color: palette.blue, fontSize: 16, fontWeight: '900' },
  staffApplicationNoticeText: { color: palette.muted, fontSize: 14, fontWeight: '600', lineHeight: 20 },
  adminPortalHeader: { alignItems: 'center', gap: 9, paddingTop: 20, paddingBottom: 14 },
  adminPortalIcon: {
    width: 58,
    height: 58,
    borderRadius: 19,
    backgroundColor: palette.splashTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminToolbar: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  adminRefreshButton: {
    width: 48,
    height: 48,
    borderRadius: 13,
    backgroundColor: palette.blueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminApplicationCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.faint,
    backgroundColor: palette.card,
    padding: 17,
    gap: 6,
  },
  adminApplicantName: { color: palette.ink, fontSize: 17, fontWeight: '900' },
  adminApplicantEmail: { color: palette.muted, fontSize: 13, fontWeight: '700' },
  adminApplicantDate: { color: palette.muted, fontSize: 12, fontWeight: '600', marginTop: 2 },
  adminApplicationActions: { flexDirection: 'row', gap: 10, marginTop: 9 },
  adminApproveButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 13,
    backgroundColor: palette.greenDark,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  adminActionText: { color: palette.white, fontSize: 13, fontWeight: '900' },
  adminRejectButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
    backgroundColor: palette.dangerSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  adminRejectText: { color: palette.danger, fontSize: 13, fontWeight: '900' },
  signOutButton: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
    backgroundColor: palette.dangerSurface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  signOutButtonText: { color: palette.danger, fontSize: 15, fontWeight: '900' },
  deleteAccountLink: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteAccountLinkText: { color: palette.danger, fontSize: 13, fontWeight: '800' },
  deleteAccountCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.dangerBorder,
    backgroundColor: palette.dangerSoft,
    padding: 16,
    gap: 13,
  },
  deleteAccountTitle: { color: palette.danger, fontSize: 17, fontWeight: '900' },
  deleteAccountMessage: { color: palette.ink, fontSize: 13, fontWeight: '600', lineHeight: 19 },
  deleteAccountButton: {
    minHeight: 50,
    borderRadius: 15,
    backgroundColor: palette.dangerAction,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteAccountButtonText: { color: palette.white, fontSize: 14, fontWeight: '900' },
  deleteAccountCancel: { minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  deleteAccountCancelText: { color: palette.muted, fontSize: 14, fontWeight: '800' },
  profileBar: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  eyebrow: { color: palette.muted, fontSize: 14, fontWeight: '700' },
  h1: { color: palette.ink, fontSize: 26, fontWeight: '900', letterSpacing: 0 },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.avatarSurface,
  },
  avatarText: { color: palette.white, fontSize: 16, fontWeight: '900' },
  card: {
    borderRadius: 18,
    backgroundColor: palette.card,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: palette.faint,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  badge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  badgeWarm: { backgroundColor: palette.warm },
  badgeGreen: { backgroundColor: palette.mint },
  badgeText: { fontSize: 12, fontWeight: '900' },
  badgeWarmText: { color: palette.amber },
  badgeGreenText: { color: palette.greenDark },
  cardTitle: { color: palette.ink, fontSize: 18, fontWeight: '900', minWidth: 0, flexShrink: 1 },
  cardSubtle: { color: palette.muted, fontSize: 14, fontWeight: '600', minWidth: 0, flexShrink: 1 },
  cardRule: { height: 1, backgroundColor: palette.faint },
  footerRow: { flexDirection: 'row', justifyContent: 'space-between' },
  metaText: { color: palette.muted, fontSize: 13, fontWeight: '800' },
  sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: '900', marginTop: 4, letterSpacing: -0.1 },
  actionRow: { flexDirection: 'row', gap: 12 },
  actionRowCompact: { flexDirection: 'column', gap: 10 },
  actionCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 108,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'space-between',
    overflow: 'hidden',
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  actionCardCompact: {
    minHeight: 78,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  actionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mint,
  },
  actionIconCompact: {
    width: 34,
    height: 34,
    borderRadius: 10,
  },
  actionIconText: { color: palette.blue, fontSize: 22, fontWeight: '900' },
  actionLabel: { color: palette.ink, fontSize: 15, fontWeight: '900', lineHeight: 20, minWidth: 0, flexShrink: 1 },
  actionLabelCompact: { fontSize: 14, lineHeight: 18 },
  listItem: {
    minHeight: 72,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  successIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successIconText: { color: palette.green, fontWeight: '900' },
  appointmentQueueSummary: {
    width: '100%',
    borderRadius: 24,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 22,
    gap: 18,
  },
  appointmentQueueTitle: { color: palette.ink, fontSize: 21, lineHeight: 28, fontWeight: '900' },
  queueProgressTrack: { height: 14, justifyContent: 'center' },
  queueProgressRail: {
    position: 'absolute',
    left: 6,
    right: 6,
    height: 3,
    borderRadius: 2,
    backgroundColor: palette.faint,
  },
  queueProgressRailActive: {
    right: undefined,
    backgroundColor: palette.greenDark,
  },
  queueProgressDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  queueProgressDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: palette.faint,
    backgroundColor: palette.card,
  },
  queueProgressDotActive: {
    borderColor: palette.greenDark,
    backgroundColor: palette.greenDark,
  },
  queueProgressLabels: { flexDirection: 'row', justifyContent: 'space-between', gap: 4 },
  queueProgressLabel: {
    flex: 1,
    color: palette.muted,
    fontSize: 9,
    lineHeight: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  queueProgressLabelActive: { color: palette.greenDark, fontWeight: '900' },
  appointmentQueueMetrics: { flexDirection: 'row', gap: 14 },
  appointmentQueueMetric: {
    flex: 1,
    minHeight: 92,
    borderRadius: 18,
    padding: 16,
    justifyContent: 'center',
    gap: 8,
    backgroundColor: palette.bg,
  },
  appointmentQueueMetricLabel: { color: palette.muted, fontSize: 13, fontWeight: '700' },
  appointmentQueueMetricValue: { color: palette.greenDark, fontSize: 20, lineHeight: 26, fontWeight: '900' },
  itemTitle: { color: palette.ink, fontSize: 15, fontWeight: '900', minWidth: 0, flexShrink: 1 },
  itemSubtle: { color: palette.muted, fontSize: 12, lineHeight: 17, fontWeight: '600', minWidth: 0, flexShrink: 1 },
  header: {
    minHeight: 64,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
  },
  backText: { color: palette.ink, fontSize: 32, lineHeight: 34 },
  headerTitle: { color: palette.ink, fontSize: 20, fontWeight: '900', flexShrink: 1 },
  headerSubtitle: { color: palette.muted, fontSize: 12, fontWeight: '700', flexShrink: 1 },
  staffHeader: {
    minHeight: 71,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  staffTitleGroup: { flex: 1, minWidth: 0, gap: 2 },
  smallIconButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
  },
  smallIconText: { color: palette.ink, fontSize: 24, lineHeight: 26 },
  serviceList: { gap: 12 },
  serviceCard: {
    minHeight: 87,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  serviceIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceIconText: { color: palette.greenDark, fontSize: 11, fontWeight: '900' },
  serviceInfo: { flex: 1, gap: 4 },
  chevron: { color: palette.muted, fontSize: 28 },
  calendarCard: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 20,
    gap: 16,
  },
  monthRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  monthControls: { flexDirection: 'row', gap: 8 },
  monthArrowButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.bg,
  },
  monthArrowButtonDisabled: { opacity: 0.4 },
  monthArrows: { color: palette.greenDark, fontSize: 20, fontWeight: '900' },
  weekRow: { flexDirection: 'row', justifyContent: 'space-between' },
  weekDay: { width: 36, textAlign: 'center', color: palette.muted, fontSize: 12, fontWeight: '900' },
  dateGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  dayCell: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  dayCellDisabled: { opacity: 0.35 },
  dayCellEmpty: { width: 36, height: 36 },
  dayCellSelected: { backgroundColor: palette.green },
  dayText: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  dayTextSelected: { color: palette.white },
  timeSlot: {
    height: 54,
    borderRadius: 16,
    paddingHorizontal: 16,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeSlotSelected: { backgroundColor: palette.green, borderColor: palette.green },
  timeText: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  timeTextSelected: { color: palette.white },
  settingsCard: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 12,
  },
  settingsOptionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  settingsDay: {
    minWidth: 44,
    minHeight: 48,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.bg,
  },
  settingsDaySelected: { backgroundColor: palette.greenDark },
  settingsDayText: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  settingsDayTextSelected: { color: palette.white },
  settingsChip: {
    minHeight: 48,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.bg,
  },
  settingsTimeRow: { flexDirection: 'row', gap: 12 },
  settingsTimeField: { flex: 1, minWidth: 0, gap: 10 },
  settingsPeriodRow: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    borderRadius: 12,
    padding: 3,
    gap: 3,
    backgroundColor: palette.bg,
  },
  settingsPeriodButton: {
    minWidth: 56,
    minHeight: 48,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  settingsPeriodButtonSelected: { backgroundColor: palette.green },
  settingsPeriodText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  settingsPeriodTextSelected: {
    color: palette.white,
  },
  settingsValidation: { color: palette.danger, fontSize: 12, fontWeight: '700', lineHeight: 18 },
  settingsCalendarHeader: { gap: 12 },
  settingsMonthControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  settingsMonthButton: { minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  settingsMonthArrow: { color: palette.greenDark, fontSize: 20, fontWeight: '900', paddingHorizontal: 8 },
  settingsMonthLabel: { color: palette.ink, fontSize: 14, fontWeight: '900' },
  settingsCalendarGrid: { marginHorizontal: -8, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  settingsCalendarWeekday: { width: '14.2857%', paddingVertical: 8, color: palette.muted, fontSize: 11, fontWeight: '900', textAlign: 'center' },
  settingsCalendarDate: { width: '14.2857%', minHeight: 48, marginVertical: 2, borderRadius: 999, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.mint },
  settingsCalendarDateOutside: { backgroundColor: 'transparent' },
  settingsCalendarDatePast: { opacity: 0.35 },
  settingsCalendarDateClosed: { backgroundColor: palette.dangerSoft },
  settingsCalendarDateText: { color: palette.blue, fontSize: 13, fontWeight: '800' },
  settingsCalendarDateOutsideText: { color: palette.muted },
  settingsCalendarDateClosedText: { color: palette.danger },
  bookingDateUnavailable: { opacity: 0.25 },
  bookingMonthControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  bookingMonthButton: { minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  bookingMonthArrow: { color: palette.greenDark, fontSize: 20, fontWeight: '900', paddingHorizontal: 8 },
  bookingMonthLabel: { color: palette.ink, fontSize: 14, fontWeight: '900' },
  bookingCalendarGrid: { marginHorizontal: -8, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  bookingWeekday: { width: '14%', paddingVertical: 8, color: palette.muted, fontSize: 11, fontWeight: '900', textAlign: 'center' },
  bookingDate: { width: '14.2857%', minHeight: 48, marginVertical: 2, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  bookingDateSelected: { backgroundColor: palette.greenDark },
  bookingDateText: { color: palette.ink, fontSize: 13, fontWeight: '800' },
  bookingDateTextSelected: { color: palette.white },
  bookingTimeSelectors: { flexDirection: 'row', gap: 12 },
  bookingTimeSelector: { flex: 1, minWidth: 0, gap: 6 },
  bookingTimeDropdown: { minHeight: 48, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: palette.faint, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: palette.card },
  bookingTimeDropdownDisabled: { opacity: 0.5 },
  bookingTimeDropdownText: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  bookingTimeDropdownPlaceholder: { color: palette.muted },
  bookingTimeDropdownArrow: { color: palette.greenDark, fontSize: 12, fontWeight: '900' },
  bookingTimeDropdownOptions: { maxHeight: 220, borderRadius: 12, borderWidth: 1, borderColor: palette.faint, backgroundColor: palette.card },
  bookingTimeDropdownOption: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: palette.faint },
  bookingTimeDropdownOptionSelected: { backgroundColor: palette.mint },
  bookingTimeDropdownOptionText: { color: palette.ink, fontSize: 14, fontWeight: '700' },
  bookingTimeDropdownOptionTextSelected: { color: palette.blue, fontWeight: '900' },
  queueHero: {
    alignItems: 'center',
    paddingVertical: 28,
    borderRadius: 22,
    backgroundColor: palette.green,
    gap: 4,
  },
  queueLabel: { color: palette.white, fontSize: 13, fontWeight: '900' },
  queueNumber: { color: palette.white, fontSize: 58, fontWeight: '900', letterSpacing: 0 },
  queueSubtle: { color: palette.white, fontSize: 14, fontWeight: '800' },
  queueActionHint: {
    color: palette.muted,
    backgroundColor: palette.card,
    borderRadius: 14,
    padding: 14,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  progressTrack: { height: 10, borderRadius: 10, backgroundColor: palette.faint, overflow: 'hidden' },
  progressFill: { width: '68%', height: '100%', backgroundColor: palette.green },
  queueRow: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderRadius: 18,
    padding: 14,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
  },
  ticketBox: {
    width: 48,
    height: 44,
    borderRadius: 14,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: palette.greenDark,
    backgroundColor: palette.mint,
    fontWeight: '900',
  },
  profileHeader: { alignItems: 'center', gap: 8, paddingVertical: 28 },
  profileVerificationBadge: {
    minHeight: 30,
    borderRadius: 999,
    paddingHorizontal: 11,
    backgroundColor: palette.mint,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  profileVerificationBadgePending: { backgroundColor: palette.warm },
  profileVerificationText: { color: palette.greenDark, fontSize: 12, fontWeight: '900' },
  profileVerificationTextPending: { color: palette.amber },
  largeAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.avatarSurface,
  },
  largeAvatarText: { color: palette.white, fontSize: 28, fontWeight: '900' },
  profileRow: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 4,
  },
  statRow: { flexDirection: 'row', gap: 12 },
  statCard: {
    flex: 1,
    minHeight: 82,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 4,
  },
  compactCard: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 10,
  },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  rowStart: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  pillButton: {
    minHeight: 48,
    borderRadius: 999,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  pillButtonText: { color: palette.white, fontSize: 12, fontWeight: '900' },
  outlinePillButton: {
    minHeight: 48,
    borderRadius: 999,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.faint,
    backgroundColor: palette.card,
  },
  outlinePillButtonText: { color: palette.ink, fontSize: 12, fontWeight: '900' },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.green },
  });
}

const lightStyles = createStyles(lightPalette);

export function useQueuelessStyles() {
  return lightStyles;
}
