import { StyleSheet } from 'react-native';

import { palette } from './palette';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.bg },
  screen: { flex: 1, backgroundColor: palette.bg },
  splash: {
    flex: 1,
    justifyContent: 'space-between',
    backgroundColor: '#F4F7FB',
    paddingHorizontal: 20,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  splashCenter: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  logoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: palette.blue,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 4,
  },
  ticketStack: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: '#EAF0FF',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
  },
  ticketMark: { color: palette.blue, fontSize: 34, fontWeight: '900' },
  brand: { color: palette.ink, fontSize: 36, fontWeight: '900', letterSpacing: 0 },
  tagline: { color: palette.muted, fontSize: 16, fontWeight: '600' },
  splashFooter: { alignItems: 'center', gap: 18, paddingBottom: 24, width: '100%' },
  dots: { flexDirection: 'row', gap: 8 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.blue },
  dotMuted: { opacity: 0.35 },
  footerText: { color: palette.muted, fontSize: 12, fontWeight: '700' },
  primaryButton: {
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    shadowColor: palette.greenDark,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryButtonMuted: { opacity: 0.72 },
  splashButton: { width: 200 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
  secondaryButton: {
    height: 52,
    borderWidth: 1,
    borderColor: palette.faint,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.card,
  },
  secondaryButtonText: { color: palette.ink, fontSize: 16, fontWeight: '900' },
  loginHero: { alignItems: 'center', paddingTop: 40, paddingBottom: 48, gap: 8 },
  schoolShield: {
    width: 64,
    height: 64,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.blue,
  },
  schoolShieldText: { color: '#FFFFFF', fontSize: 24, fontWeight: '900' },
  schoolName: { marginTop: 8, color: palette.ink, fontSize: 22, fontWeight: '900' },
  mutedCenter: { color: palette.muted, textAlign: 'center', fontSize: 14, fontWeight: '600' },
  form: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    paddingHorizontal: 24,
    gap: 16,
  },
  fieldBlock: { gap: 8 },
  label: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  inputShell: {
    height: 52,
    borderWidth: 1,
    borderColor: palette.faint,
    borderRadius: 16,
    backgroundColor: palette.card,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 12,
  },
  inputShellError: { borderColor: palette.danger, backgroundColor: palette.dangerSoft },
  input: { flex: 1, color: palette.ink, fontSize: 14, fontWeight: '600' },
  fieldErrorRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  fieldError: { color: palette.danger, fontSize: 12, fontWeight: '700', flex: 1 },
  errorBanner: {
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: palette.dangerSoft,
    borderWidth: 1,
    borderColor: '#F7C9D0',
  },
  errorBannerText: { color: palette.danger, fontSize: 13, fontWeight: '700', flex: 1, lineHeight: 18 },
  errorDismiss: { color: palette.danger, fontSize: 12, fontWeight: '900' },
  eyeText: { color: palette.muted, fontSize: 11, fontWeight: '900' },
  linkText: { color: palette.blue, textAlign: 'right', fontWeight: '800' },
  loginActions: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    marginTop: 'auto',
    paddingHorizontal: 24,
    paddingBottom: 28,
    gap: 20,
  },
  dividerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  divider: { flex: 1, height: 1, backgroundColor: palette.faint },
  dividerText: { color: palette.muted, fontSize: 13, fontWeight: '700' },
  content: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 28,
    gap: 18,
  },
  profileBar: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  eyebrow: { color: palette.muted, fontSize: 14, fontWeight: '700' },
  h1: { color: palette.ink, fontSize: 26, fontWeight: '900', letterSpacing: 0 },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  avatarText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
  card: {
    borderRadius: 18,
    backgroundColor: palette.card,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: palette.faint,
    shadowColor: '#24324A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  badge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  badgeWarm: { backgroundColor: palette.warm },
  badgeGreen: { backgroundColor: palette.mint },
  badgeText: { fontSize: 12, fontWeight: '900' },
  badgeWarmText: { color: palette.amber },
  badgeGreenText: { color: palette.greenDark },
  cardTitle: { color: palette.ink, fontSize: 18, fontWeight: '900' },
  cardSubtle: { color: palette.muted, fontSize: 14, fontWeight: '600' },
  cardRule: { height: 1, backgroundColor: palette.faint },
  footerRow: { flexDirection: 'row', justifyContent: 'space-between' },
  metaText: { color: palette.muted, fontSize: 13, fontWeight: '800' },
  sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: '900', marginTop: 4 },
  actionRow: { flexDirection: 'row', gap: 12 },
  actionCard: {
    flex: 1,
    minHeight: 110,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    justifyContent: 'space-between',
    shadowColor: '#24324A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  actionIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mint,
  },
  actionIconText: { color: palette.blue, fontSize: 22, fontWeight: '900' },
  actionLabel: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  listItem: {
    minHeight: 72,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    shadowColor: '#24324A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  successIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successIconText: { color: palette.green, fontWeight: '900' },
  itemTitle: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  itemSubtle: { color: palette.muted, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  header: {
    minHeight: 64,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
  },
  backText: { color: palette.ink, fontSize: 32, lineHeight: 34 },
  headerTitle: { color: palette.ink, fontSize: 20, fontWeight: '900', flexShrink: 1 },
  headerSubtitle: { color: palette.muted, fontSize: 12, fontWeight: '700', flexShrink: 1 },
  staffHeader: {
    minHeight: 71,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  staffTitleGroup: { flex: 1, minWidth: 0, gap: 2 },
  smallIconButton: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
  },
  smallIconText: { color: palette.ink, fontSize: 24, lineHeight: 26 },
  serviceList: { gap: 12 },
  serviceCard: {
    minHeight: 87,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  serviceIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: palette.mint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceIconText: { color: palette.greenDark, fontSize: 11, fontWeight: '900' },
  serviceInfo: { flex: 1, gap: 4 },
  chevron: { color: palette.muted, fontSize: 28 },
  calendarCard: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 20,
    gap: 16,
  },
  monthRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  monthArrows: { color: palette.green, fontSize: 20, fontWeight: '900' },
  weekRow: { flexDirection: 'row', justifyContent: 'space-between' },
  weekDay: { width: 36, textAlign: 'center', color: palette.muted, fontSize: 12, fontWeight: '900' },
  dateGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  dayCell: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  dayCellSelected: { backgroundColor: palette.green },
  dayText: { color: palette.ink, fontSize: 14, fontWeight: '800' },
  dayTextSelected: { color: '#FFFFFF' },
  timeSlot: {
    height: 54,
    borderRadius: 16,
    paddingHorizontal: 16,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeSlotSelected: { backgroundColor: palette.green, borderColor: palette.green },
  timeText: { color: palette.ink, fontSize: 15, fontWeight: '900' },
  timeTextSelected: { color: '#FFFFFF' },
  queueHero: {
    alignItems: 'center',
    paddingVertical: 28,
    borderRadius: 22,
    backgroundColor: palette.green,
    gap: 4,
  },
  queueLabel: { color: '#DDEDE3', fontSize: 13, fontWeight: '900' },
  queueNumber: { color: '#FFFFFF', fontSize: 58, fontWeight: '900', letterSpacing: 0 },
  queueSubtle: { color: '#F2FAF4', fontSize: 14, fontWeight: '800' },
  progressTrack: { height: 10, borderRadius: 10, backgroundColor: palette.faint, overflow: 'hidden' },
  progressFill: { width: '68%', height: '100%', backgroundColor: palette.green },
  queueRow: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderRadius: 18,
    padding: 14,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
  },
  ticketBox: {
    width: 48,
    height: 44,
    borderRadius: 14,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: palette.greenDark,
    backgroundColor: palette.mint,
    fontWeight: '900',
  },
  profileHeader: { alignItems: 'center', gap: 8, paddingVertical: 28 },
  largeAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  largeAvatarText: { color: '#FFFFFF', fontSize: 28, fontWeight: '900' },
  profileRow: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 4,
  },
  statRow: { flexDirection: 'row', gap: 12 },
  statCard: {
    flex: 1,
    minHeight: 82,
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 4,
  },
  compactCard: {
    borderRadius: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.faint,
    padding: 16,
    gap: 10,
  },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  rowStart: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  pillButton: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  pillButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  outlinePillButton: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.faint,
    backgroundColor: palette.card,
  },
  outlinePillButtonText: { color: palette.ink, fontSize: 12, fontWeight: '900' },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.green },
  bottomBar: {
    width: '100%',
    minHeight: 76,
    paddingTop: 12,
    paddingBottom: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    backgroundColor: palette.card,
    borderTopWidth: 1,
    borderTopColor: palette.faint,
    shadowColor: '#24324A',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 8,
  },
  tabItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 4,
  },
  tabIcon: { color: palette.muted, fontSize: 18, fontWeight: '900' },
  tabLabel: { color: palette.muted, fontSize: 12, fontWeight: '800' },
  tabActive: { color: palette.green },
});
